# Cloud Build configuration for Trading Execution Engine
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.simple'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-execution-engine:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-execution-engine:latest'
      - '.'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'trading-execution-engine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trading-execution-engine:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,PAPER_TRADING=true,SEBI_COMPLIANCE=enabled,LOG_LEVEL=INFO'

# Store the built images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/trading-execution-engine:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/trading-execution-engine:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
