constraints:
  max_drawdown: 0.15
  max_position_size: 0.5
  min_sharpe: 0.5
  min_trades: 10
optimization:
  objective: risk_adjusted_return
  secondary_objectives:
  - sharpe_ratio
  - win_rate
  weight_risk_adjusted: 0.5
  weight_sharpe: 0.3
  weight_win_rate: 0.2
parameters:
  bb_period:
    max: 50
    min: 10
    optimal_hint: 20
    step: 5
    type: range
  bb_std:
    optimal_hint: 2.0
    type: list
    values:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
  exit_threshold:
    max: 2.0
    min: 0.5
    optimal_hint: 1.0
    step: 0.25
    type: range
strategy:
  class: BollingerBandsStrategy
  description: Bollinger Bands with adaptive parameters
  name: BollingerBandsStrategy
  type: mean_reversion
