# This workflow runs CI checks for the trading-execution-engine project.
# It installs dependencies, runs linting, type checks, and tests on every push or PR to main. 
# It also builds and deploys the application to Google Cloud Run on pushes to main.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install pytest pytest-cov flake8 black mypy isort
        pip install -e .
    - name: Lint with black
      run: |
        black --check .
    - name: Type check with mypy
      run: |
        mypy src/
    - name: Test with pytest
      run: |
        pytest
